#!/bin/bash

yui-compressor -o content.min.js --type js content.js
yui-compressor -o auto-link.min.js --type js auto-link.js

echo "Minified"

rm hackernews-sorter.zip

zip hackernews-sorter.zip *.min.js background.html icon2.png manifest.json README

echo "Done."
